In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
car_data = pd.read_csv("Cardetails.csv")
car_data

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0

In [4]:
car_data.shape

(8128, 13)

In [5]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   object
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   object
 5   seller_type    8128 non-null   object
 6   transmission   8128 non-null   object
 7   owner          8128 non-null   object
 8   mileage        7907 non-null   object
 9   engine         7907 non-null   object
 10  max_power      7913 non-null   object
 11  torque         7906 non-null   object
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB

In [6]:
car_data.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'torque',
       'seats'],
      dtype='object')

In [7]:
car_data.describe()

              year  selling_price     km_driven        seats
count  8128.000000   8.128000e+03  8.128000e+03  7907.000000
mean   2013.804011   6.382718e+05  6.981951e+04     5.416719
std       4.044249   8.062534e+05  5.655055e+04     0.959588
min    1983.000000   2.999900e+04  1.000000e+00     2.000000
25%    2011.000000   2.549990e+05  3.500000e+04     5.000000
50%    2015.000000   4.500000e+05  6.000000e+04     5.000000
75%    2017.000000   6.750000e+05  9.800000e+04     5.000000
max    2020.000000   1.000000e+07  2.360457e+06    14.000000

In [8]:
car_data.isna().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [9]:
car_data.dropna(inplace = True)

In [10]:
car_data.shape

(7906, 13)

In [11]:
car_data.duplicated().sum()

np.int64(1189)

In [12]:
car_data.drop_duplicates(inplace = True)

In [13]:
car_data.shape

(6717, 13)

In [14]:
car_data.sample(5)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
2326,Maruti Wagon R LXI BS IV,2016,350000,70000,Petrol,Individual,Manual,First Owner,20.51 kmpl,998 CC,67.04 bhp,90Nm@ 3500rpm,5.0
4069,Hyundai Verna 1.6 CRDi S Option,2016,850000,120000,Diesel,Individual,Manual,First Owner,23.9 kmpl,1582 CC,126.32 bhp,259.8Nm@ 1900-2750rpm,5.0
4493,Maruti Wagon R VXI Optional,2015,360000,34000,Petrol,Individual,Manual,First Owner,20.51 kmpl,998 CC,67.04 bhp,90Nm@ 3500rpm,5.0
210,Maruti Swift Dzire AMT VXI BS IV,2018,700000,7800,Petrol,Individual,Automatic,First Owner,22.0 kmpl,1197 CC,81.80 bhp,113Nm@ 4200rpm,5.0
7103,Maruti Ertiga VXI,2014,425000,80000,Petrol,Individual,Manual,Third Owner,16.02 kmpl,1373 CC,93.7 bhp,130Nm@ 4000rpm,7.0

In [15]:
#creating our data unique which is called encoding

for col in car_data.columns :
    print("Unique colums "+col)
    print(car_data[col])
    print("*******************************************")

Unique colums name
0                  Maruti Swift Dzire VDI
1            Skoda Rapid 1.5 TDI Ambition
2                Honda City 2017-2020 EXi
3               Hyundai i20 Sportz Diesel
4                  Maruti Swift VXI BSIII
                      ...
8121    Maruti Wagon R VXI BS IV with ABS
8122           Hyundai i20 Magna 1.4 CRDi
8123                    Hyundai i20 Magna
8124                Hyundai Verna CRDi SX
8125               Maruti Swift Dzire ZDi
Name: name, Length: 6717, dtype: object
*******************************************
Unique colums year
0       2014
1       2014
2       2006
3       2010
4       2007
        ...
8121    2013
8122    2014
8123    2013
8124    2007
8125    2009
Name: year, Length: 6717, dtype: int64
*******************************************
Unique colums selling_price
0       450000
1       370000
2       158000
3       225000
4       130000
         ...
8121    260000
8122    475000
8123    320000
8124    135000
8125    382000
Name: selling_price, Length: 6717, dtype: int64
*******************************************
Unique colums km_driven
0       145500
1       120000
2       140000
3       127000
4       120000
         ...
8121     50000
8122     80000
8123    110000
8124    119000
8125    120000
Name: km_driven, Length: 6717, dtype: int64
*******************************************
Unique colums fuel
0       Diesel
1       Diesel
2       Petrol
3       Diesel
4       Petrol
         ...
8121    Petrol
8122    Diesel
8123    Petrol
8124    Diesel
8125    Diesel
Name: fuel, Length: 6717, dtype: object
*******************************************
Unique colums seller_type
0       Individual
1       Individual
2       Individual
3       Individual
4       Individual
           ...
8121    Individual
8122    Individual
8123    Individual
8124    Individual
8125    Individual
Name: seller_type, Length: 6717, dtype: object
*******************************************
Unique colums transmission
0       Manual
1       Manual
2       Manual
3       Manual
4       Manual
         ...
8121    Manual
8122    Manual
8123    Manual
8124    Manual
8125    Manual
Name: transmission, Length: 6717, dtype: object
*******************************************
Unique colums owner
0                First Owner
1               Second Owner
2                Third Owner
3                First Owner
4                First Owner
                ...
8121            Second Owner
8122            Second Owner
8123             First Owner
8124    Fourth & Above Owner
8125             First Owner
Name: owner, Length: 6717, dtype: object
*******************************************
Unique colums mileage
0        23.4 kmpl
1       21.14 kmpl
2        17.7 kmpl
3        23.0 kmpl
4        16.1 kmpl
           ...
8121     18.9 kmpl
8122    22.54 kmpl
8123     18.5 kmpl
8124     16.8 kmpl
8125     19.3 kmpl
Name: mileage, Length: 6717, dtype: object
*******************************************
Unique colums engine
0       1248 CC
1       1498 CC
2       1497 CC
3       1396 CC
4       1298 CC
         ...
8121     998 CC
8122    1396 CC
8123    1197 CC
8124    1493 CC
8125    1248 CC
Name: engine, Length: 6717, dtype: object
*******************************************
Unique colums max_power
0           74 bhp
1       103.52 bhp
2           78 bhp
3           90 bhp
4         88.2 bhp
           ...
8121      67.1 bhp
8122     88.73 bhp
8123     82.85 bhp
8124       110 bhp
8125      73.9 bhp
Name: max_power, Length: 6717, dtype: object
*******************************************
Unique colums torque
0                  190Nm@ 2000rpm
1             250Nm@ 1500-2500rpm
2           12.7@ 2,700(kgm@ rpm)
3        22.4 kgm at 1750-2750rpm
4           11.5@ 4,500(kgm@ rpm)
                  ...
8121                90Nm@ 3500rpm
8122        219.7Nm@ 1500-2750rpm
8123             113.7Nm@ 4000rpm
8124    24@ 1,900-2,750(kgm@ rpm)
8125               190Nm@ 2000rpm
Name: torque, Length: 6717, dtype: object
*******************************************
Unique colums seats
0       5.0
1       5.0
2       5.0
3       5.0
4       5.0
       ...
8121    5.0
8122    5.0
8123    5.0
8124    5.0
8125    5.0
Name: seats, Length: 6717, dtype: float64
*******************************************

In [16]:
#creating a function to shorten the car's name to make encoding easier
def model_name(carName):
    carName = carName.split()[0]
    return carName

print(model_name(" Maruti Swift Dzire VDI"))

Maruti

In [17]:
#to apply the function on dataframe
car_data["name"] = car_data["name"].apply(model_name)

In [18]:
car_data["name"].head()

0     Maruti
1      Skoda
2      Honda
3    Hyundai
4     Maruti
Name: name, dtype: object

In [19]:
# del car_data["torque"]
car_data.drop(columns = ["torque"], inplace = True)

In [20]:
#chenging from alphanumeric to numeric
def clean_data(value) : 
    value = value.split(' ')[0]
    value = value.strip()
    if value == '':
        value = 0 
    return float(value)

In [21]:
car_data["mileage"] = car_data["mileage"].apply(clean_data)
car_data["engine"] = car_data["engine"].apply(clean_data)
car_data["max_power"] = car_data["max_power"].apply(clean_data)

In [22]:
car_data.sample(5)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
367,Hyundai,2010,140000,70000,Petrol,Individual,Manual,Fourth & Above Owner,20.36,1197.0,78.9,5.0
5264,Tata,2019,450000,25000,Petrol,Individual,Manual,First Owner,20.30,1199.0,84.0,5.0
5554,Maruti,2015,600000,100000,Diesel,Individual,Manual,First Owner,26.59,1248.0,74.0,5.0
3187,Hyundai,2013,165000,45000,Petrol,Individual,Manual,Second Owner,21.10,814.0,55.2,5.0
6644,Renault,2016,315000,60000,Petrol,Individual,Manual,Second Owner,23.01,999.0,67.0,5.0

In [23]:
le = LabelEncoder()
car_data["fuel"] = le.fit_transform(car_data["fuel"])
car_data["seller_type"] = le.fit_transform(car_data["seller_type"])
car_data["name"] = le.fit_transform(car_data["name"])
car_data["owner"] = le.fit_transform(car_data["owner"])
car_data["transmission"] = le.fit_transform(car_data["transmission"])

In [24]:
car_data.sample(5)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
3939,27,2018,750000,25000,3,1,1,0,17.00,1198.0,108.5,5.0
7209,20,2005,98000,70000,3,1,1,2,18.90,998.0,67.1,5.0
7462,19,2011,550000,80000,1,1,1,2,12.05,2179.0,120.0,9.0
1341,4,2012,170000,90000,1,1,1,0,25.44,936.0,57.6,5.0
378,10,2016,550000,56494,3,2,1,0,18.20,1199.0,88.7,5.0

In [25]:
model = LinearRegression()

input_data = car_data.drop(columns=['selling_price'])
output_data = car_data['selling_price']

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    input_data,
    output_data,
    test_size= 0.2
)

In [27]:
model.fit(X_train,y_train)

LinearRegression()

In [28]:
predict = model.predict(X_test)
print(predict)

[614734.22333218 106609.53410839 592744.21047031 ... 487493.63214641
 428036.79814139 169518.08752035]

In [29]:
X_train.head(1)

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
3346,6,2017,31100,3,0,1,0,22.7,799.0,53.64,5.0

In [30]:
input_data_model = pd.DataFrame(
    [[28,2010,100000, 1, 1,1,2,12.8,2494.0,102.0,7.0]],
    columns=['name','year','km_driven','fuel','seller_type','transmission','owner','mileage','engine','max_power','seats']
)

In [31]:
input_data_model

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,28,2010,100000,1,1,1,2,12.8,2494.0,102.0,7.0

In [32]:
model.predict(input_data_model)

array([533506.81511106])

In [33]:
car_data["max_power"].sort_values()

6007     32.8
3466     32.8
6846     34.2
1661     34.2
1330     34.2
        ...
4787    270.9
5962    272.0
134     280.0
148     282.0
170     400.0
Name: max_power, Length: 6717, dtype: float64

In [35]:
import pickle as pk

In [36]:
pk.dump(model,open("model.pkl","wb"))